url: "https://latrobe-design-system.github.io"
languageCode: en
title: "La Trobe Design System"

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: ltucss/_sass
exclude:
    - build.sh
    - server.sh
defaults:
    -
        scope:
          path: "" # an empty string here means all files in the project
        values:
          layout: "default"
